name: Phimosis
version: 1.0
main: Phimosis.Main
author: Ehwar
description: Magia Starozytnych Elfow pozwala Ehwarowi na zostanie godnym nastepca khajickiego Boga

commands:
  kupkwarc:
  kupkosci:
  kupjasnopyl:
  kupzloto:
  kupdiamenty:
  kupczerwonyproszek:
  kupsnieg:
  kuppiaskowiec:
  kupkamien:
  kupszlam:
  kupplomiennyproszek:
  kupakacje:
  kupciemnydab:
  kupjungle:
  kupbrzoze:
  kupswierk:
  kupdab:
  kuplze:
  kupelytre:
  kupnetherowacegle:
  kupczerwonanetherowacegle:
  kuppryzmaryn:
  kupciemnypryzmaryn:
  kuppryzmarynowacegle:
  kuplatarnie:
  sprzedajziemie:
  sprzedajzloto:
  sprzedajbruk:
  sprzedajdiamenty:
  sprzedajpiasek:
  sprzedajzelazo:
  sprzedajwegiel:
  sprzedajkrzesiwo:
  sprzedajdab:
  sprzedajjungle:
  chwalaJP2:
  morphingtime:
  pogoda:
  czas:
  wolagrzmota:
  alkhajit:
  papuga: